# Generated by Django 5.2.8 on 2025-11-23 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='about',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='property',
            name='amenities',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='property',
            name='configuration',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='property',
            name='developer',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='property',
            name='map_embed_url',
            field=models.URLField(blank=True),
        ),
    ]
